### ISSUE TITLE
Build Fails - Missing file `main.js`

### ISSUE THREAD

**Issue by austinnichols101** [JMGonzalezR/Todo#1]
Build Fails.  Screenshot below.

npm v 2.15.8
node v4.4.7

![image](https://cloud.githubusercontent.com/assets/6962379/18419306/a09e2da4-7825-11e6-9d20-b2f04acf1ec9.png)

**Comment by concernedrat** [comment]
+1 main.js missing

**Comment by concernedrat** [comment]
@JMGonzalezR ,Advice: Always tag your latest stable commit to avoid an unstable HEAD status.

**Comment by JMGonzalezR** [comment]
Done, i upload the main.js and test all the steps of install and run of the repo, all is ok

**Comment by concernedrat** [comment]
Whenever I try to run npm run dev an error is thrown:

`const {app, BrowserWindow} = require('electron');
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
`

**Comment by austinnichols101** [comment]
Working.

I like this boilerplate as a reference:

https://github.com/chentsulin/electron-react-boilerplate

The people that built the boilerplate did a very good job.  There are many
things that we can use.

Try the following:
- Run `npm dev` - both processes in a single window.
- Run `npm run package` or `npm run package-all`.  They have created a very
  nice packaging process.

I have a version of this template that I've modified which adds support for:
- Livescript
- ES6 Annotations/Decorators
- react-hot-loader.

Michael
